[project]
name = "iki-lho-testing-web-gawe-selenium"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "selenium>=4.36.0",
]
